function s = defaultPlotColors()
% Colours of the traces in the multi-plot figures.
    s = struct( 'O', [1 0 1], ... 
                'P', [0 1 0], ...
                'R', [0 0 0], ...
                'E', [1 0 0], ...
                'D', [1 0.5 0], ...
                'D0', [0 0 1], ...
                'D1', [0 0.5 0.5], ...
                'DO', [0 0 1], ...
                'DP', [0 0.5 0.5] ...
              );
end
